E-Library/E-Library/urls.py
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^$", include("homepage.urls")),
    re_path(r"^booksearch/", include("booksearch.urls")),
    re_path(r"^checkinbooks/", include("checkinbooks.urls")),
    re_path(r"^addborrowers/", include("addborrowers.urls")),
    re_path(r"^payfine/", include("payfine.urls")),
]

E-Library/booksearch/urls.py
from django.urls import include, re_path
from . import views

app_name = 'booksearch'

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
]

E-Library/payfine/urls.py
from django.urls import include, re_path
from . import views

app_name = 'payfine'

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
]

E-Library/booksearch/models.py
from __future__ import unicode_literals

from django.db import models


class Authors(models.Model):
    author = models.ForeignKey('BookAuthors', models.DO_NOTHING, db_column='Author_id', primary_key=True)
    name = models.CharField(db_column='Name', max_length=255)

    class Meta:
        managed = False
        db_table = 'authors'


class Book(models.Model):
    isbn = models.CharField(db_column='Isbn', primary_key=True, max_length=10)
    title = models.CharField(db_column='Title', max_length=255, blank=True, null=True)
    availability = models.IntegerField(db_column='Availability')

    class Meta:
        managed = False
        db_table = 'book'


class BookAuthors(models.Model):
    author_id = models.AutoField(db_column='Author_id', primary_key=True)
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='Isbn', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_authors'


class BookLoans(models.Model):
    loan_id = models.AutoField(db_column='Loan_id', primary_key=True)
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='Isbn', blank=True, null=True)
    card = models.ForeignKey('Borrower', models.DO_NOTHING, db_column='Card_id', blank=True, null=True)
    date_out = models.DateField(db_column='Date_out', blank=True, null=True)
    due_date = models.DateField(db_column='Due_date', blank=True, null=True)
    date_in = models.DateField(db_column='Date_in', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_loans'


class Borrower(models.Model):
    card_id = models.AutoField(db_column='Card_id', primary_key=True)
    ssn = models.CharField(db_column='Ssn', unique=True, max_length=9)
    bname = models.CharField(db_column='Bname', max_length=255, blank=True, null=True)
    address = models.CharField(db_column='Address', max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=14, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'borrower'

E-Library/booksearch/views.py
from django.shortcuts import render
from django.db import connection
from .models import Book, Authors, BookAuthors


cursor = connection.cursor()

def index(request):
	books = ""
	message = ""
	get = True
	temp = 0
	if(request.method == "POST"):
		if('search' in request.POST):
			get = False
			keywords = request.POST['search'].split(',')
			comparision = ""
			for keyword in keywords:
				keyword = keyword.strip()
				keyword = "%" + keyword + "%"
				if(comparision != ""):
					comparision += " AND "
				comparision += "(BkAthr.Isbn LIKE '"+keyword+"' OR BkAthr.Title LIKE '"+keyword+"' OR BkAthr.authors LIKE '"+keyword+"')"

			query = "SELECT BkAthr.Isbn, BkAthr.Title, BkAthr.authors, BkAthr.Availability FROM (SELECT Book.Isbn, Book.Title, GROUP_CONCAT(Authors.Name) authors, Book.Availability FROM Book,Book_Authors,Authors WHERE Book.Isbn = Book_Authors.Isbn AND Book_Authors.Author_id = Authors.Author_id GROUP BY Book.Isbn) AS BkAthr WHERE "+comparision
			cursor.execute(query)
			books = cursor.fetchall()
			return render(request,'booksearch/index.html',{'books':books,'message':"",'get':get})

		elif('cardno' in request.POST):
			keywords = request.POST['cardno'].split(',')
			print(keywords)
			cardno = keywords[0]
			isbn = keywords[1]
			print(cardno)
			query = "SELECT COUNT(Card_id) FROM Borrower WHERE Card_id = '"+cardno+"' GROUP BY Card_id"
			cursor.execute(query)

			if(cursor.fetchone() != None):
				query = "SELECT COUNT(Loan_id) FROM Book_Loans WHERE Book_Loans.Card_id = '"+str(cardno)+"' AND Book_Loans.Date_in IS NULL GROUP BY Book_Loans.Card_id"
				cursor.execute(query)
				result = cursor.fetchone()
				print(result)
				if(result == None):
					query = "SELECT Book.Availability FROM Book WHERE Book.Isbn = '"+isbn+"'"
					cursor.execute(query)
					availability = cursor.fetchone()
					print(availability)
					#temp = availability[0] - 1
					if(availability[0] > 0):
						temp = availability[0]-1

						print(temp)
						query = 'INSERT INTO Book_Loans(Isbn, Card_id, Date_out, Due_date, Date_in) VALUES("'+ isbn +'","'+ str(cardno) +'",CURDATE(),DATE_ADD(Date_out,INTERVAL 14 DAY),NULL)'
						cursor.execute(query)
						query = 'UPDATE Book SET Book.Availability = '+str(temp)+' WHERE Book.isbn = "'+isbn+'"'
						cursor.execute(query)
						message = "Successfully checked out book. Return within 14 days to avoid fine"
					else:
						message = "Book is not available"
				else:
					query = "SELECT Book.Availability FROM Book WHERE Book.Isbn = '"+isbn+"'"
					cursor.execute(query)
					availability1 = cursor.fetchone()
					temp1 = availability1[0] - 1
					print(availability1)
					if(result[0] < 3):

						query = 'INSERT INTO Book_Loans(Isbn, Card_id, Date_out, Due_date, Date_in) VALUES("'+ isbn +'","'+ str(cardno) +'",CURDATE(),DATE_ADD(Date_out,INTERVAL 14 DAY),NULL)'
						cursor.execute(query)
						query = 'UPDATE Book SET Book.Availability = '+str(temp1)+' WHERE Book.isbn = "'+isbn+'"'
						cursor.execute(query)
						message = "Successfully checked out book. Return within 14 days to avoid fine"
					else:
						message = "Maximum of only 3 books can be checked out"
			else:
				message = "Invalid Card Number."

			return render(request,'booksearch/index.html',{'books':books,'message':message,'get':get})

		else:
			print(request.POST)
			return render(request,'booksearch/index.html',{'books':books,'message':message,'get':get})

	else:
		return render(request,'booksearch/index.html',{'books':books,'message':message,'get':get})

E-Library/booksearch/templates/booksearch/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Book Search</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="../">E-Library</a>
	    </div>
	    <ul class="nav navbar-nav">
	      <li><a href="../booksearch">Book Search</a></li>
	      <li><a href="../checkinbooks">Check-In</a></li>
	      <li><a href="../payfine">Pay Fine</a></li>
	      <li><a href="../addborrowers">Add Borrowers</a></li>
	    </ul>
	  </div>
	</nav>
	<section align="center">
		<h1>
			Search for Books
		</h1>

		<form action="{% url 'booksearch:index' %}" class="form-inline" method="post">
			<div class="form-group">
				{% csrf_token %}
				<input type="text" name="search" class="form-control" value="" />
				<input type="submit" class="btn btn-success" name="searchbtn">
			</div>
		</form>

		{% if books %}	
			<div class="container">
				<h3>Here are all books available</h3>
				<table class="table table-striped">
					<tr>
						<th>Isbn</th>
						<th>Title</th>
						<th>Author</th>
						<th>Available</th>
						<th>Check out</th>
					</tr>
					{% for book in books %}
					<tr>
						<td>{{ book.0 }}</td>
						<td>{{ book.1 }}</td>
						<td>{{ book.2 }}</td>
						<td>
							{% if book.3 > 1 %}
								Yes
							{% else %}
								No
							{% endif %}
						</td>
						<td>
							<form action="{% url 'booksearch:index' %}" method="POST">
								{% csrf_token %}
								<input type="hidden" name='cardno' id={{book.0}} />
								<button onclick="askCardNo({{book.0}});" class="btn" name="checkout" type="submit">Check Out</button>
							</form>
							
						</td>
					</tr>
					{% endfor %}
				</table>
			</div>
		{% else %}
			{% if get == False %}
				<h3>No Books Available</h3>
			{% endif %}
		{% endif %}

		<div id="loanInfo">
			{% if message %}
				{{ message }}
			{% endif %}
		</div>

		<script type="text/javascript">
			function askCardNo(isbn)
			{
				var card_no = prompt("Enter Card Number");
				document.getElementById(isbn).value = card_no +','+isbn;
			}
		</script>
	</section>
</body>
</html>