E-Library/E-Library/urls.py
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^$", include("homepage.urls")),
    re_path(r"^booksearch/", include("booksearch.urls")),
    re_path(r"^checkinbooks/", include("checkinbooks.urls")),
    re_path(r"^addborrowers/", include("addborrowers.urls")),
    re_path(r"^payfine/", include("payfine.urls")),
]

E-Library/checkinbooks/urls.py
from django.urls import include, re_path
from . import views

app_name = 'checkinbooks'

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
]

E-Library/payfine/urls.py
from django.urls import include, re_path
from . import views

app_name = 'payfine'

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
]

E-Library/checkinbooks/models.py
from __future__ import unicode_literals

from django.db import models


class Authors(models.Model):
    author = models.ForeignKey('BookAuthors', models.DO_NOTHING, db_column='Author_id', primary_key=True)
    name = models.CharField(db_column='Name', max_length=255)

    class Meta:
        managed = False
        db_table = 'authors'


class Book(models.Model):
    isbn = models.CharField(db_column='Isbn', primary_key=True, max_length=10)
    title = models.CharField(db_column='Title', max_length=255, blank=True, null=True)
    availability = models.IntegerField(db_column='Availability')

    class Meta:
        managed = False
        db_table = 'book'


class BookAuthors(models.Model):
    author_id = models.AutoField(db_column='Author_id', primary_key=True)
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='Isbn', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_authors'


class BookLoans(models.Model):
    loan_id = models.AutoField(db_column='Loan_id', primary_key=True)
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='Isbn', blank=True, null=True)
    card = models.ForeignKey('Borrower', models.DO_NOTHING, db_column='Card_id', blank=True, null=True)
    date_out = models.DateField(db_column='Date_out', blank=True, null=True)
    due_date = models.DateField(db_column='Due_date', blank=True, null=True)
    date_in = models.DateField(db_column='Date_in', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_loans'


class Borrower(models.Model):
    card_id = models.AutoField(db_column='Card_id', primary_key=True)
    ssn = models.CharField(db_column='Ssn', unique=True, max_length=9)
    bname = models.CharField(db_column='Bname', max_length=255, blank=True, null=True)
    address = models.CharField(db_column='Address', max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=14, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'borrower'


class Fines(models.Model):
    loan = models.ForeignKey(BookLoans, models.DO_NOTHING, db_column='Loan_id', primary_key=True)
    fine_amt = models.FloatField(db_column='Fine_amt')

    class Meta:
        managed = False
        db_table = 'fines'

E-Library/checkinbooks/views.py
from django.shortcuts import render
from django.db import connection

cursor = connection.cursor()

def index(request):
	books = ""
	message = ""
	get = True
	if(request.method == "POST"):
		if('checkin' in request.POST):
			get = False
			keywords = request.POST['checkin'].split(',')
			comparision = ""
			for keyword in keywords:
				keyword = keyword.strip()
				keyword = "%" + keyword + "%"
				if(comparision != ""):
					comparision += " AND "
				comparision += "(BkAthr.Isbn LIKE '"+keyword+"' OR BkAthr.Title LIKE '"+keyword+"' OR BkAthr.authors LIKE '"+keyword+"' OR BkAthr.Card_id LIKE '"+keyword+"' OR BkAthr.Bname LIKE '"+keyword+"' OR BkAthr.Ssn LIKE '"+keyword+"')"

			query = "SELECT BkAthr.Isbn, BkAthr.Title, BkAthr.authors, BkAthr.Card_id, BkAthr.Bname, BkAthr.Ssn, BkAthr.Loan_id FROM (SELECT Book.Isbn, Book.Title, GROUP_CONCAT(Authors.Name) authors, Borrower.Card_id, Borrower.Bname, Borrower.Ssn, Book_Loans.Loan_id FROM Book,Book_Authors,Authors,Borrower,Book_Loans WHERE Book.Isbn = Book_Authors.Isbn AND Book_Authors.Author_id = Authors.Author_id AND Book.Isbn = Book_Loans.Isbn AND Borrower.Card_id = Book_Loans.Card_id AND Book_Loans.Date_in IS NULL GROUP BY Book.Isbn, Borrower.Card_id, Book_Loans.Loan_id) AS BkAthr WHERE "+ comparision
			cursor.execute(query)
			books = cursor.fetchall()

			return render(request,'checkinbooks/index.html',{'books':books,'message':message,'get':get})
		elif('loanid' in request.POST):
			get = False
			loan_id = request.POST['loanid']
			isbn = request.POST['isbnrtbk'] 
			query = "UPDATE Book_Loans SET Date_in = CURDATE() WHERE Loan_id = '"+ loan_id +"'"
			cursor.execute(query)

			query = "SELECT DATEDIFF(Date_in,Due_date) FROM Book_Loans WHERE Book_Loans.Loan_id = '"+loan_id+"'"
			cursor.execute(query)
			days = cursor.fetchone()[0]

			query1 = "SELECT Book.Availability FROM Book WHERE Book.Isbn = '" + isbn + "'"
			cursor.execute(query1)
			availability = cursor.fetchone()
			temp = availability[0] + 1

			if(days > 0):
				fine_amt = days*0.25;
				message = "Your fine of amount "+str(fine_amt)+" is due "
				query = "SELECT Paid FROM Fines WHERE Loan_id = '"+ loan_id +"' GROUP BY Loan_id"
				cursor.execute(query)
				fineExist = cursor.fetchone()
				print(fineExist)
				if(fineExist == None):
					query = "INSERT INTO Fines(Loan_id,Fine_amt,Paid) VALUES('"+ loan_id +"','"+ str(fine_amt) +"','0')"
					cursor.execute(query)
				else:
					if(fineExist[0] == 0):
						query = "UPDATE Fines SET Fine_amt = '"+ str(fine_amt) +"' WHERE Loan_id = '"+loan_id+"'"
						cursor.execute(query)

			query = "UPDATE Book SET Availability = '"+str(temp)+"' WHERE Isbn = '"+isbn+"'"
			cursor.execute(query)
			message += "successfully checked in book."
			return render(request,'checkinbooks/index.html',{'Books':books,'message':message, 'get':get})
		else:
			message = "Please try again."
			return render(request,'checkinbooks/index.html',{'Books':books,'message':message, 'get':get})	
	else:
		return render(request,'checkinbooks/index.html',{'Books':books,'message':message, 'get':get})

E-Library/checkinbooks/templates/checkinbooks/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Checkin Books</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="../">E-Library</a>
	    </div>
	    <ul class="nav navbar-nav">
	      <li><a href="../booksearch">Book Search</a></li>
	      <li><a href="../checkinbooks">Check-In</a></li>
	      <li><a href="../payfine">Pay Fine</a></li>
	      <li><a href="../addborrowers">Add Borrowers</a></li>
	    </ul>
	  </div>
	</nav>
	<section align="center">
		<h1>Search for Books to Check-In</h1>

		<form action="{% url 'checkinbooks:index' %}" method="post" class="form-inline">
			<div class="form-group">	
				{% csrf_token %}
				<input type="text" name="checkin" class="form-control" />
				<input type="submit" class="btn btn-success" name="searchbtn">
			</div>
		</form>

		{% if books %}	
			<div class="container">
				<h3>Heres what we found</h3>
				<table class="table table-striped">
				<tr>
					<th>Isbn</th>
					<th>Title</th>
					<th>Author</th>
					<th>Card Number</th>
					<th>Borrower Name</th>
					<th>Ssn</th>
					<th>Check In</th>
				</tr>
				{% for book in books %}
				<tr>
					<td>{{ book.0 }}</td>
					<td>{{ book.1 }}</td>
					<td>{{ book.2 }}</td>
					<td>{{ book.3 }}</td>
					<td>{{ book.4 }}</td>
					<td>{{ book.5 }}</td>
					<td>
						<form action="{% url 'checkinbooks:index' %}" method="POST" id="card_no_form">
							{% csrf_token %}
							<input type="hidden" name="isbnrtbk" value = {{book.0}} />
							<input type="hidden" name="loanid" value = {{book.6}} />
							<input type="submit" name="checkinbtn" class="btn" value="Check-In" />
						</form>
					</td>
				</tr>
				{% endfor %}
				</table>
			</div>
		{% else %}
			{% if get == False %}
				<h3>No Books Available</h3>
			{% endif %}
		{% endif %}

		<div id="loanInfo">
			{% if message %}
				{{ message }}
			{% endif %}
		</div>
	</section>
</body>
</html>