E-Library/E-Library/urls.py
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^$", include("homepage.urls")),
    re_path(r"^booksearch/", include("booksearch.urls")),
    re_path(r"^checkinbooks/", include("checkinbooks.urls")),
    re_path(r"^addborrowers/", include("addborrowers.urls")),
    re_path(r"^payfine/", include("payfine.urls")),
]

E-Library/addborrowers/urls.py
from django.urls import include, re_path
from . import views

app_name = 'addborrowers'

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
]

E-Library/payfine/urls.py
from django.urls import include, re_path
from . import views

app_name = 'payfine'

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
]

E-Library/addborrowers/models.py
from __future__ import unicode_literals

from django.db import models

class Borrower(models.Model):
    card_id = models.AutoField(db_column='Card_id', primary_key=True)
    ssn = models.CharField(db_column='Ssn', unique=True, max_length=9)
    bname = models.CharField(db_column='Bname', max_length=255, blank=True, null=True)
    address = models.CharField(db_column='Address', max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=14, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'borrower'

E-Library/addborrowers/views.py
from django.shortcuts import render
from django.db import connection
from .models import Borrower

cursor = connection.cursor()

def index(request):
	ssnexist = False
	message = ""
	if(request.method == "POST"):
		fname = request.POST['fname']
		ssn = request.POST['ssn']
		address = request.POST['address']
		phone = request.POST['phone']

		query = "SELECT Ssn FROM Borrower WHERE Ssn = '" + ssn + "'"
		cursor.execute(query)

		if(cursor.fetchone() != None):
			ssnexist = True
		else:
			query = 'INSERT INTO Borrower(Ssn,Bname,Address,Phone) VALUES("'+ ssn +'","'+ fname +'","'+ address +'","'+ phone +'");'
			cursor.execute(query)
			message = "Successfully added the borrower"

	return render(request,'addborrowers/index.html',{'ssnexist':ssnexist,'message':message})

E-Library/addborrowers/templates/addborrowers/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Borrowers</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="../">E-Library</a>
	    </div>
	    <ul class="nav navbar-nav">
	      <li><a href="../booksearch">Book Search</a></li>
	      <li><a href="../checkinbooks">Check-In</a></li>
	      <li><a href="../payfine">Pay Fine</a></li>
	      <li><a href="../addborrowers">Add Borrowers</a></li>
	    </ul>
	  </div>
	</nav>
	<section align="center">
		<h1>Please fill the information below</h1>
		<table align="center">
			<form align="center" action="{% url 'addborrowers:index' %}" method="POST" class="form-inline">
				<div class="form-group">
					{% csrf_token %}
					<tr>
						<td>Full Name</td>
						<td><input type="text" name="fname" class="form-control" required="1" /></td>
					</tr>
					<tr>
						<td>SSN</td>
						<td><input type="text" name="ssn" class="form-control" required="1" /></td>
					</tr>
					<tr>
						<td>Address</td>
						<td><input type="text" name="address" class="form-control" required="1" /></td>
					</tr>
					<tr>
						<td>Phone</td>
						<td><input type="text" name="phone" class="form-control" required="1" /></td>
					</tr>
					<tr>
						<td colspan="2" align="center"><input type="submit" class="btn btn-success" value="Add" name="addborrower"></td>
					</tr>
				</div>
			</form>
		</table>

		{% if ssnexist %}
			SSN already exists, please try again
		{% else %}
			{% if message %}
				{{message}}
			{% endif %}
		{% endif %}
	</section>
</body>
</html>