E-Library/E-Library/urls.py
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^$", include("homepage.urls")),
    re_path(r"^booksearch/", include("booksearch.urls")),
    re_path(r"^checkinbooks/", include("checkinbooks.urls")),
    re_path(r"^addborrowers/", include("addborrowers.urls")),
    re_path(r"^payfine/", include("payfine.urls")),
]

E-Library/payfine/urls.py
from django.urls import include, re_path
from . import views

app_name = 'payfine'

urlpatterns = [
    re_path(r'^$', views.index, name="index"),
]

E-Library/payfine/models.py
from __future__ import unicode_literals

from django.db import models


class Authors(models.Model):
    author = models.ForeignKey('BookAuthors', models.DO_NOTHING, db_column='Author_id', primary_key=True)
    name = models.CharField(db_column='Name', max_length=255)

    class Meta:
        managed = False
        db_table = 'authors'


class Book(models.Model):
    isbn = models.CharField(db_column='Isbn', primary_key=True, max_length=10)
    title = models.CharField(db_column='Title', max_length=255, blank=True, null=True)
    availability = models.IntegerField(db_column='Availability')

    class Meta:
        managed = False
        db_table = 'book'


class BookAuthors(models.Model):
    author_id = models.AutoField(db_column='Author_id', primary_key=True)
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='Isbn', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_authors'


class BookLoans(models.Model):
    loan_id = models.AutoField(db_column='Loan_id', primary_key=True)
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='Isbn', blank=True, null=True)
    card = models.ForeignKey('Borrower', models.DO_NOTHING, db_column='Card_id', blank=True, null=True)
    date_out = models.DateField(db_column='Date_out', blank=True, null=True)
    due_date = models.DateField(db_column='Due_date', blank=True, null=True)
    date_in = models.DateField(db_column='Date_in', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_loans'


class Borrower(models.Model):
    card_id = models.AutoField(db_column='Card_id', primary_key=True)
    ssn = models.CharField(db_column='Ssn', unique=True, max_length=9)
    bname = models.CharField(db_column='Bname', max_length=255, blank=True, null=True)
    address = models.CharField(db_column='Address', max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=14, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'borrower'


class Fines(models.Model):
    loan = models.ForeignKey(BookLoans, models.DO_NOTHING, db_column='Loan_id', primary_key=True)
    fine_amt = models.FloatField(db_column='Fine_amt')

    class Meta:
        managed = False
        db_table = 'fines'

E-Library/payfine/views.py
from django.shortcuts import render
from .models import Borrower,BookLoans,Fines
from django.db import connection

cursor = connection.cursor()

def index(request):
	fines = ""
	message = ""
	get = True
	if(request.method == 'POST'):
		if('searchfines' in request.POST):
			get = False
			keywords = request.POST['searchfines'].split(',')
			comparision = ""
			for keyword in keywords:
				keyword = keyword.strip()
				keyword = "%" + keyword + "%"
				if(comparision != ""):
					comparision += " AND "
				comparision += "(Borrower.Card_id LIKE '"+keyword+"' OR Borrower.Ssn LIKE '"+keyword+"' OR Borrower.Bname LIKE '"+keyword+"')"

			query = "SELECT Borrower.Card_id, Borrower.Ssn, Borrower.Bname, SUM(Fines.Fine_amt) Totalfine FROM Borrower,Book_Loans,Fines WHERE Borrower.Card_id = Book_Loans.Card_id AND Book_Loans.Loan_id = Fines.Loan_id AND Fines.Paid = '0' AND Book_Loans.Date_in IS NOT NULL GROUP BY Borrower.Card_id HAVING "+ comparision
			cursor.execute(query)
			fines = cursor.fetchall()
			return render(request,'payfine/index.html',{'fines':fines,'message':message,'get':get})

		elif('refreshfines' in request.POST):
			query = "SELECT Loan_id, DATEDIFF(CURDATE(),Due_date)*0.25 difference FROM Book_Loans WHERE DATEDIFF(CURDATE(),Due_date)*0.25 > '0'"
			cursor.execute(query)
			results = cursor.fetchall()
			for result in results:
				query = "SELECT Loan_id FROM Fines WHERE Loan_id = '"+str(result[0])+"'"
				cursor.execute(query)
				if(cursor.fetchone() == None):
					query = "INSERT INTO Fines(Loan_id,Fine_amt,Paid) VALUES('"+ str(result[0]) +"', '"+str(result[1])+"', '0')"
					cursor.execute(query)
				else:
					query = "UPDATE Fines SET Fines.Fine_amt = '"+str(result[1])+"' WHERE Fines.Loan_id = '"+str(result[0])+"' AND Fines.Paid = '0'"
					cursor.execute(query)

			message = "Successfully Refreshed Fines"
			return render(request,'payfine/index.html',{'fines':fines,'message':message,'get':get})

		elif('cardnumber' in request.POST):
			cardnumber = request.POST['cardnumber']
			query = "SELECT Loan_id FROM Book_Loans WHERE Date_in IS NOT NULL AND Card_id = '"+str(cardnumber)+"'"
			cursor.execute(query)
			loanids = cursor.fetchall();
			for loanid in loanids:
				query = "UPDATE Fines SET Fines.Paid = '1' WHERE Fines.Loan_id = '"+str(loanid[0])+"' AND Fines.Paid = '0'"
				cursor.execute(query)
			message = "Payment Successful."
			return render(request,'payfine/index.html',{'fines':fines,'message':message,'get':get})

		else:
			message = "Something went wrong please try again."
			return render(request,'payfine/index.html',{'fines':fines,'message':message,'get':get})
	else:
		return render(request,'payfine/index.html',{'fines':fines,'message':message,'get':get})

E-Library/payfine/templates/payfine/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Pay Fine</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="../">E-Library</a>
	    </div>
	    <ul class="nav navbar-nav">
	      <li><a href="../booksearch">Book Search</a></li>
	      <li><a href="../checkinbooks">Check-In</a></li>
	      <li><a href="../payfine">Pay Fine</a></li>
	      <li><a href="../addborrowers">Add Borrowers</a></li>
	    </ul>
	    <form action="{% url 'payfine:index' %}" method="post">
			{% csrf_token %}
			<input type="submit" value="Refresh Fines" class="btn btn-danger navbar-btn" name="refreshfines">
		</form>
	  </div>
	</nav>
	<section align = "center">
		<h1>
			Enter Card Number, Name or Ssn
		</h1>

		<form action="{% url 'payfine:index' %}" method="post" class="form-inline">
			<div class="form-group">
				{% csrf_token %}
				<input type="text" class="form-control" name="searchfines"/>
				<input type="submit" class="btn btn-success" name="searchfinesbtn" value="Search">
			</div>
		</form>

		{% if fines %}	
			<div class="container">
				<h3>Heres what we found</h3>
				<table class="table table-striped">
				<tr>
					<th>Card Number</th>
					<th>Ssn</th>
					<th>Full Name</th>
					<th>Fine Amount</th>
					<th>Pay</th>
				</tr>
				{% for fine in fines %}
				<tr>
					<td>{{ fine.0 }}</td>
					<td>{{ fine.1 }}</td>
					<td>{{ fine.2 }}</td>
					<td>{{ fine.3 }}</td>
					<td>
						<form action="{% url 'payfine:index' %}" method="POST">
							{% csrf_token %}
							<input type="hidden" name="cardnumber" value = {{fine.0}} />
							<input type="submit" name="paybtn" class="btn btn-success" value="Pay" />
						</form>
					</td>
				</tr>
				{% endfor %}
				</table>
			</div>
		{% else %}
			{% if get == False %}
				<h3>No Fines Available</h3>
			{% endif %}
		{% endif %}

		<div id="loanInfo">
			{% if message %}
				{{ message }}
			{% endif %}
		</div>
	</section>
</body>
</html>